---
- hosts: all
  gather_facts: no

  vars:
    change_id: CHG0040003
    org: Default
    check_ssl: no
    uri: "https://{{ sn_instance }}.service-now.com/api/now/table"
    location_dbc: "200 South James street,Atlanta, GA"
    location_soc: "3260 Jay Street, Santa Clara, CA"
    bdc:
      - tower.iclabng.com
      - 7b.c0.7434.ip4.static.sl-reverse.com
    soc:
      - tower.home.lan
  tasks:
    - name: Set location as BDC
      set_fact:
        location: "{{ location_bdc }}"
      when: ansible_fqdn in bdc

    - name: Set location as SOC
      set_fact:
        location: "{{ location_soc }}"
      when: ansible_fqdn in soc

    - name: Get ServiceNow Change information
      ansible.builtin.uri:
        url: "{{ uri }}/change_request?sysparm_query=number={{ change_id }}"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
      register: change_info

    - name: Collect Change sys_id information
      ansible.builtin.set_fact:
        snow_change_sys_id: "{{ change_info.json.result.0.sys_id }}"

    - name: Get ServiceNow Task CI items
      ansible.builtin.uri:
        url: "{{ uri }}/task_ci?sysparm_query=task={{ snow_change_sys_id }}"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
      register: task_info

    - name: Check if Change has affected CIs
      ansible.builtin.set_fact:
        has_affected_cis: "{{ 'no' if task_info.json.result | length < 1 else 'yes' }}"

    - name: Get ServiceNow CI information
      ansible.builtin.uri:
        url: "{{ uri }}/cmdb_ci/{{ item.ci_item.value }}?sysparm_display_value=true"
        user: "{{ sn_username }}"
        password: "{{ sn_password }}"
      register: ci_info
      with_items:
        - "{{ task_info.json.result }}"
      when: has_affected_cis | bool

    - name: Collect affected CI
      ansible.builtin.set_fact:
        snow_affected_cis: "{{ snow_affected_cis | default({}) | combine ({item.json.result.asset_tag: item.json.result.name}) }}"
      with_items:
        - "{{ ci_info.results }}"
      when: has_affected_cis | bool

    - name: Create {{ change_id }} inventory
      awx.awx.inventory:
        name: "{{ change_id }}"
        description: "Inventory related to {{ change_id }}"
        organization: "{{ org }}"
        validate_certs: "{{ check_ssl }}"
      when: has_affected_cis | bool

    - name: Add host(s) to {{ change_id }} inventory
      vars:
        name: "{{ item.json.result.name }}"
        asset_tag: "{{ item.json.result.asset_tag }}"
      awx.awx.host:
        inventory: "{{ change_id }}"
        name: "{{ name }}"
        description: "CI from {{ change_id }}"
        validate_certs: "{{ check_ssl }}"
        variables:
          asset_tag: "{{ asset_tag }}"
      with_items:
        - "{{ ci_info.results }}"
      when:
        - has_affected_cis | bool
        - item.json.result.location.display_value == location
